WEAVIATE = "WEAVIATE"
WEAVIATE_BASE_URL = "WEAVIATE_BASE_URL"
WEAVIATE_API_KEY = "WEAVIATE_API_KEY"
WEAVIATE_CONNECTION_TIMEOUT = "WEAVIATE_CONNECTION_TIMEOUT"
WEAVIATE_READ_TIMEOUT = "WEAVIATE_READ_TIMEOUT"
WEAVIATE_BATCH_SIZE = "WEAVIATE_BATCH_SIZE"
WEAVIATE_BATCH_DYNAMIC = "WEAVIATE_BATCH_DYNAMIC"
WEAVIATE_BATCH_TIMEOUT_RETRIES = "WEAVIATE_BATCH_TIMEOUT_RETRIES"

